name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install latest .NET SDK
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.x"

      # Print .NET SDK version
      - name: Print .NET version
        run: echo `dotnet --version`

      # Restore project dependencies and build in Release mode
      - name: Restore dependencies and build RELEASE package
        working-directory: .
        run: |
          dotnet restore ./Injectify.sln
          dotnet build -c Release ./Injectify.sln